package com.github.eyrekr.y2024;

import com.github.eyrekr.AocTest;

class D08Test extends AocTest {

    D08Test() {
        constructor(D08::new);
        sample("""
                ............
                ........0...
                .....0......
                .......0....
                ....0.......
                ......A.....
                ............
                ............
                ........A...
                .........A..
                ............
                ............
                """);
        star1(14L, 376L);
        star2(34L, 1352L);
    }
}
